import re

html = open("advice.html", "r").read()

new_logic = """            // Save Chat Logic
            const chatSave = document.getElementById('chat-save');
            if (chatSave) {
                chatSave.addEventListener('click', async () => {
                    await saveConversationAsPDF();
                });
            }

            async function saveConversationAsPDF() {
                // <!-- VERIFY chatwithHK EXPOSES CONVERSATION HISTORY BEFORE DEPLOY. -->
                const currentHistory = (typeof chatwithHK !== 'undefined' && chatwithHK.history) ? chatwithHK.history : history;
                
                if (!currentHistory || currentHistory.length <= 1) {
                    alert("Nothing to save yet.");
                    return;
                }

                if (chatSave) {
                    chatSave.disabled = true;
                    chatSave.classList.add('animate-pulse');
                }

                // <!-- VERIFY /api/save-conversation EXISTS IN BACKEND. IF NOT, WIRE TO EXISTING saveConversation ENDPOINT. -->
                try {
                    await fetch('/api/save-conversation', {
                        method: 'POST',
                        headers: { 'Content-Type': 'application/json' },
                        body: JSON.stringify({ transcript: currentHistory })
                    });
                } catch (error) {
                    console.error("Server save failed. Continuing with local PDF generation.", error);
                }

                try {
                    const { jsPDF } = window.jspdf;
                    const doc = new jsPDF();
                    
                    const PDF_CONFIG = {
                        font: "helvetica",
                        primaryColor: [212, 93, 58],
                        textColor: [40, 40, 40],
                        margin: 20,
                        lineHeight: 7
                    };

                    doc.setProperties({
                        title: "Conversation with the Digital Twin — H.K. Borah",
                        author: "H.K. Borah"
                    });

                    doc.outline.add(null, "Start of Conversation", { pageNumber: 1 });

                    let y = PDF_CONFIG.margin;
                    const pageHeight = doc.internal.pageSize.getHeight();
                    const pageWidth = doc.internal.pageSize.getWidth();
                    const maxLineWidth = pageWidth - (PDF_CONFIG.margin * 2);

                    doc.setFont(PDF_CONFIG.font, "bold");
                    doc.setFontSize(16);
                    doc.setTextColor(...PDF_CONFIG.textColor);
                    doc.text("Conversation with the Digital Twin — H.K. Borah", PDF_CONFIG.margin, y);
                    y += PDF_CONFIG.lineHeight * 2;

                    doc.setFontSize(10);
                    doc.setFont(PDF_CONFIG.font, "normal");

                    for (let msg of currentHistory) {
                        const roleLabel = msg.role === 'user' ? 'YOU' : 'HK BORAH';
                        
                        if (y > pageHeight - PDF_CONFIG.margin - 20) {
                            doc.addPage();
                            y = PDF_CONFIG.margin;
                        }

                        doc.setFont(PDF_CONFIG.font, "bold");
                        if (msg.role === 'user') {
                            doc.setTextColor(...PDF_CONFIG.textColor);
                        } else {
                            doc.setTextColor(...PDF_CONFIG.primaryColor);
                        }
                        
                        doc.text(roleLabel + ":", PDF_CONFIG.margin, y);
                        y += PDF_CONFIG.lineHeight;
                        
                        doc.setFont(PDF_CONFIG.font, "normal");
                        doc.setTextColor(...PDF_CONFIG.textColor);

                        const lines = doc.splitTextToSize(msg.content, maxLineWidth);
                        for (let line of lines) {
                            if (y > pageHeight - PDF_CONFIG.margin - 20) {
                                doc.addPage();
                                y = PDF_CONFIG.margin;
                            }
                            doc.text(line, PDF_CONFIG.margin, y);
                            y += PDF_CONFIG.lineHeight;
                        }
                        y += PDF_CONFIG.lineHeight;
                    }

                    const footerText = "Generated by the user on their device. A copy is stored on hkborah.com for H.K. Borah's personal research only. No personal data was captured, and nothing has been shared with anyone else.";
                    const footerLines = doc.splitTextToSize(footerText, maxLineWidth);
                    
                    y += PDF_CONFIG.lineHeight;
                    if (y + (footerLines.length * PDF_CONFIG.lineHeight) > pageHeight - PDF_CONFIG.margin) {
                        doc.addPage();
                        y = PDF_CONFIG.margin;
                    }

                    doc.setFont(PDF_CONFIG.font, "italic");
                    doc.setFontSize(8);
                    doc.setTextColor(150, 150, 150);
                    doc.text(footerLines, PDF_CONFIG.margin, y);

                    doc.save(`HK_Borah_Conversation.pdf`);
                } catch (err) {
                    console.error("PDF Generation error:", err);
                    alert("Could not generate PDF.");
                }

                if (chatSave) {
                    chatSave.disabled = false;
                    chatSave.classList.remove('animate-pulse');
                }
            }"""

# Use regex to find and replace the block
html = re.sub(r'// Save Chat Logic.*?chatSave\.classList\.remove\(\'animate-pulse\'\);\n\s*\}', new_logic, html, flags=re.DOTALL)

with open("advice.html", "w") as f:
    f.write(html)
